### ISSUE TITLE
Your API key is visible

### ISSUE THREAD

**Issue by Ilshidur** [josealvarado/CS686-LeagueOfLegendsAnalysis#1]
Like the title said, your API key is clearly visible here : https://github.com/josealvarado/CS686-LeagueOfLegendsAnalysis/blob/master/league.py
I heavily suggest you to remove it or else malicious people can use it at their own interests.

**Comment by josealvarado** [comment]
Wow, thanks for letting me know Ilshidur. I really appreciate it!

**Comment by Ilshidur** [comment]
It's still visible in the 100th line ;-)

**Comment by mchally** [comment]
thanks Jose!
